// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	services2 "mallbots/modules/cart/application/services"
	"mallbots/modules/cart/infrastructure/repositories"
	"mallbots/modules/cart/infrastructure/rest"
	"mallbots/modules/product/application/services"
	repositories2 "mallbots/modules/product/infrastructure/repositories"
)

// Injectors from wire.go:

func InitializeCartHandler(db *pgxpool.Pool) (*rest.CartHandler, error) {
	cartRepository := repositories.NewCartRepository(db)
	productRepository := repositories2.NewProductRepository(db)
	productService := services.NewProductService(productRepository)
	cartService := services2.NewCartService(cartRepository, productService)
	cartHandler := rest.NewCartHandler(cartService)
	return cartHandler, nil
}

// wire.go:

var CartSet = wire.NewSet(repositories2.NewProductRepository, services.NewProductService, repositories.NewCartRepository, services2.NewCartService, rest.NewCartHandler)
