// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"mallbots/modules/cart/application/services"
	"mallbots/modules/cart/infrastructure/repositories"
	"mallbots/modules/cart/infrastructure/rest"
	repositories2 "mallbots/modules/product/infrastructure/repositories"
)

// Injectors from wire.go:

func InitializeCartHandler(db *pgxpool.Pool) (*rest.CartItemHandler, error) {
	cartItemRepository := repositories.NewCartItemRepository(db)
	productRepository := repositories2.NewProductRepository(db)
	cartItemService := services.NewCartItemService(cartItemRepository, productRepository)
	cartItemHandler := rest.NewCartItemHandler(cartItemService)
	return cartItemHandler, nil
}

// wire.go:

var CartSet = wire.NewSet(repositories.NewCartItemRepository, repositories2.NewProductRepository, services.NewCartItemService, rest.NewCartItemHandler)
