// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	"mallbots/modules/product/application/services"
	"mallbots/modules/product/infrastructure/repositories"
	"mallbots/modules/product/infrastructure/rest"
)

// Injectors from wire.go:

func InitializeProductHandler(db *pgxpool.Pool) (*rest.ProductHandler, error) {
	productRepository := repositories.NewProductRepository(db)
	productService := services.NewProductService(productRepository)
	productHandler := rest.NewProductHandler(productService)
	return productHandler, nil
}

// wire.go:

var ProductSet = wire.NewSet(repositories.NewProductRepository, services.NewProductService, rest.NewProductHandler)
