root = "."
tmp_dir = "tmp"

[build]
include_ext = ["go", "tpl", "tmpl", "html", "env"]
exclude_dir = [
  "assets",
  "tmp",
  "vendor",
  ".git",
  "prisma/migrations",
  "modules/contracts",
]
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = true
follow_symlink = true
full_bin = ""
delay = 1000
kill_delay = "0s"
send_interrupt = false
stop_on_error = true

# Added environment file loading
env_file = ".env"
cmd = "go build -o ./tmp/main ./cmd/api/main.go"
bin = "./tmp/main"

# Pass environment variables to the binary
args_bin = []

[log]
time = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
