// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/jackc/pgx/v5/pgxpool"
	services2 "mallbots/modules/cart/application/services"
	repositories2 "mallbots/modules/cart/infrastructure/repositories"
	services3 "mallbots/modules/order/application/services"
	"mallbots/modules/order/infrastructure/repositories"
	"mallbots/modules/order/infrastructure/rest"
	"mallbots/modules/product/application/services"
	repositories3 "mallbots/modules/product/infrastructure/repositories"
)

// Injectors from wire.go:

func InitializeOrderHandler(db *pgxpool.Pool) (*rest.OrderHandler, error) {
	orderRepository := repositories.NewOrderRepository(db)
	cartRepository := repositories2.NewCartRepository(db)
	productRepository := repositories3.NewProductRepository(db)
	productService := services.NewProductService(productRepository)
	cartService := services2.NewCartService(cartRepository, productService)
	orderService := services3.NewOrderService(orderRepository, cartService)
	orderHandler := rest.NewOrderHandler(orderService)
	return orderHandler, nil
}

// wire.go:

var OrderSet = wire.NewSet(repositories3.NewProductRepository, services.NewProductService, repositories2.NewCartRepository, services2.NewCartService, repositories.NewOrderRepository, services3.NewOrderService, rest.NewOrderHandler)
